TYPO3:
  Flow:
    resource:
      targets:
        localWebDirectoryPersistentResourcesTarget:
          target: 'Mw\SymlinkPublishing\Resource\Target\FileSystemSymlinkTarget'
          targetOptions:
            relativeSymlinks: TRUE
        localWebDirectoryStaticResourcesTarget:
          target: 'Mw\SymlinkPublishing\Resource\Target\FileSystemSymlinkTarget'
          targetOptions:
            relativeSymlinks: TRUE